version: '3.8'

services:
  tarot-backend:
    build: .
    container_name: tarot_backend_app
    restart: unless-stopped
    env_file: .env # Load environment variables from .env file
    environment:
      - NODE_ENV=production # Ensure production mode
      # MONGODB_URI should point to the mongo service within the Docker network
      - MONGODB_URI=mongodb://mongo:27017/tarot_prod 
      # PORT is already set in Dockerfile/config, but can be overridden here if needed
      # - PORT=5000
      - CORS_ORIGIN=http://localhost:3000 # Thêm giá trị cụ thể cho CORS_ORIGIN
    ports:
      # Ánh xạ cổng host 5005 tới cổng 5005 của container (nơi app lắng nghe theo .env và config.js)
      - "5005:5005"
    depends_on:
      - mongo
    networks:
      - tarot-network
    volumes: # Thêm phần volumes
      - .:/app # Ánh xạ thư mục hiện tại (.) của host vào /app của container
      # Loại trừ node_modules để sử dụng bản đã cài trong image, tránh xung đột hệ điều hành
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/health"] # Kiểm tra endpoint /health trên cổng nội bộ
      interval: 30s # Kiểm tra mỗi 30 giây
      timeout: 10s # Chờ tối đa 10 giây cho phản hồi
      retries: 3 # Thử lại 3 lần nếu thất bại
      start_period: 60s # Chờ 60 giây sau khi container khởi động trước khi bắt đầu kiểm tra
    tty: true
    stdin_open: true

  mongo:
    image: mongo:latest
    container_name: tarot_mongo_db
    restart: unless-stopped
    # Optional: Add authentication
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    #   MONGO_INITDB_DATABASE: tarot_prod # Optional: create a default DB
    ports:
      - "27017:27017" # Expose MongoDB port only if needed for external access (use with caution)
    volumes:
      - mongo-data:/data/db # Persist data
    networks:
      - tarot-network

volumes:
  mongo-data:
    driver: local

networks:
  tarot-network:
    driver: bridge
